version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  publisher:
    build: ./publisher
    container_name: publisher
    ports:
      - "8000:8000"
    depends_on:
      - redis
  subscriber:
    build: ./subscriber
    container_name: subscriber
    depends_on:
      - redis


