services:
  redis:
    image: redis:latest
    container_name: redis-server

  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    container_name: publisher
    command: uvicorn publisher:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    container_name: subscriber
    depends_on:
      - redis
