services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    container_name: publisher
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    container_name: subscriber
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


